apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: web-questionnaire
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: denisktv/quest-back:v0.0.6
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service/questionnaire"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: web-questionnaire
  labels:
    app: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend
